### PR TITLE
This fixes compilation in OSX.

### PR DESCRIPTION
**Pull request by Adenilson**
The required flag in clang to enable C++11 is different than gcc
as also there was an implicit include (i.e. std::string) in GNU libs.

Environment: XCode 7.2, OSX 10.11 (El Capitan).

### CODE REVIEW

**Comment by Adenilson** [comment]
Dear friend

When you got some spare time, would you mind to have a look on this patch?

This is required to make avcpp to compile in OSX.

Cheers


Adenilson Cavalcanti

**Comment by Adenilson** [comment]
As OSX is an important platform, maybe we could support it in future releases?

**Comment by h4tr3d** [comment]
@Adenilson Hi, thanks for patch. It looks good.
> As OSX is an important platform, maybe we could support it in future releases?
I have no any OSX installations to test.

**Comment by Adenilson** [comment]
I could help to test it in OSX (and maybe in iOS too).
:-)

**Comment by h4tr3d** [comment]
I agree :-)

**Pull request merged**
