### PR TITLE
Examples: set rescaler parameters, use setAverageFrameRate() for MKV

### PR DESCRIPTION
**Pull request by rkfg**
Killing two birds with one stone, let's show an example of rescale and setting average FPS, also fixes the code so it actually works.

### CODE REVIEW

**Comment by h4tr3d** [comment]
@rkfg, so, what will be happens if we will setup avg_frame_rate always?

**Comment by rkfg** [comment]
I guess nothing bad would happen, but I can't possibly imagine all use cases. FFmpeg copies these values separately when it copies streams and uses `r_frame_rate` mostly to get the rate from the input stream and `avg_frame_rate` to set it to the output stream. It's confusing, yes. I think unless someone with better understanding of these internals clear the situation up, we should stick to the original plan, i.e. just have to separate methods for both fields.

**Comment by h4tr3d** [comment]
Ok, I agree. Currently I have no time to dig it and I have no active projects that uses FFmpeg/avcpp.

Also, thanks for good observation: input streams - r_frame_rate, output streams - avg_frame_rate.

**Comment by h4tr3d** [comment]
In any case, thanks for contributions :-)

**Pull request merged**
